### ISSUE TITLE
TODO: article about Eclipse IDE

### ISSUE THREAD

**Issue by bkis** [DH-Cologne/java-wegweiser#12]
`Eclipse-IDE.md` has to be written. Nothing there.

**Comment by Demirro** [comment]
Es wäre sinnvoll die üblichen Shortcuts und die Generatoren (Getter & Setter, Overrides etc.) zu beschreiben. Oder auch generelle Quality of Life Tipps und Tricks wie im Seminar am 19.05.2020 angesprochen, die Abstände bei Getter und Setter. Siehe: https://stackoverflow.com/questions/10417407/put-space-between-auto-generated-getters-setters-in-eclipse

**Comment by bkis** [comment]
Gute Idee, ja, das sollte da alles mit rein.

**Comment by bkis** [comment]
done.

**Comment by bkis** [comment]
@all-contributors please add @Demirro for ideas
