### ISSUE TITLE
Article about naming conventions missing

### ISSUE THREAD

**Issue by bkis** [DH-Cologne/java-wegweiser#20]
see `Naming-Conventions.md`

**Comment by bkis** [comment]
Closed via #42 by @mkamphausen

**Comment by jkamphausen** [comment]
Closed by @jkamphausen 🔀 😅

**Comment by bkis** [comment]
Huch, stimmt, gar nicht bemerkt! Ist aber auch sehr ähnlich :roll_eyes:  
Dann musst du ja auch noch auf die Contributor-Liste!

**Comment by bkis** [comment]
@all-contributors please add @jkamphausen for content and example

**Comment by bkis** [comment]
Erledigt!

**Comment by jkamphausen** [comment]
🙌
