### ISSUE TITLE
Missing link "Objektorientierung"

### ISSUE THREAD

**Issue by ch1190** [DH-Cologne/java-wegweiser#67]
Under this section: https://dh-cologne.github.io/java-wegweiser/articles/Die-Programmiersprache-Java.html#objektorientierung is a missing link under "Objektorientierung". When you click on the key word Objektorientierung, only 404 appears.
Don't know if a chapter to object orientation exists by now or not, couldn't find it.

**Comment by bkis** [comment]
Thanks for the hint!
